// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperFormulaRestAPI.Data;

#nullable disable

namespace SuperFormulaRestAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220526002048_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SuperFormulaRestAPI.Data.Entities.Member", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Premium")
                        .HasColumnType("float");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = new Guid("25210260-a4fe-4a54-80c5-33073c9122e0"),
                            Address = "300 S Rankin St, Richmond, VA, 23224",
                            CreateDate = new DateTime(2022, 5, 25, 20, 20, 47, 869, DateTimeKind.Local).AddTicks(1987),
                            DriverLicenseNumber = "DL1000001",
                            EffectiveDate = new DateTime(2022, 6, 24, 20, 20, 47, 869, DateTimeKind.Local).AddTicks(2015),
                            ExpirationDate = new DateTime(2022, 11, 25, 20, 20, 47, 869, DateTimeKind.Local).AddTicks(2016),
                            FirstName = "Jon",
                            LastName = "Jones",
                            Premium = 80.950000000000003
                        },
                        new
                        {
                            MemberId = new Guid("76da447e-227f-4507-a66e-b881178cf254"),
                            Address = "300 S Rankin St, Richmond, VA, 23224",
                            CreateDate = new DateTime(2022, 5, 25, 20, 20, 47, 869, DateTimeKind.Local).AddTicks(2020),
                            DriverLicenseNumber = "DL1000002",
                            EffectiveDate = new DateTime(2022, 6, 24, 20, 20, 47, 869, DateTimeKind.Local).AddTicks(2021),
                            ExpirationDate = new DateTime(2022, 11, 25, 20, 20, 47, 869, DateTimeKind.Local).AddTicks(2023),
                            FirstName = "Peter",
                            LastName = "Parker",
                            Premium = 80.950000000000003
                        },
                        new
                        {
                            MemberId = new Guid("07e795a2-4df9-4885-80c6-a1a4ada01483"),
                            Address = "300 S Rankin St, Richmond, VA, 23224",
                            CreateDate = new DateTime(2022, 5, 25, 20, 20, 47, 869, DateTimeKind.Local).AddTicks(2026),
                            DriverLicenseNumber = "DL1000003",
                            EffectiveDate = new DateTime(2022, 6, 24, 20, 20, 47, 869, DateTimeKind.Local).AddTicks(2027),
                            ExpirationDate = new DateTime(2022, 11, 25, 20, 20, 47, 869, DateTimeKind.Local).AddTicks(2028),
                            FirstName = "Tony",
                            LastName = "Stark",
                            Premium = 80.950000000000003
                        });
                });

            modelBuilder.Entity("SuperFormulaRestAPI.Data.Entities.Policy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehicleManufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleYear")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.HasIndex("MemberId");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            PolicyId = new Guid("b2ff9388-8f8e-49dc-8d1d-4f9cca557b00"),
                            MemberId = new Guid("25210260-a4fe-4a54-80c5-33073c9122e0"),
                            VehicleManufacturer = "Toyota",
                            VehicleModel = "Camry",
                            VehicleName = "My Car",
                            VehicleYear = 1978
                        },
                        new
                        {
                            PolicyId = new Guid("0a662ea9-e0e2-4fdf-9157-bc1aca27b588"),
                            MemberId = new Guid("76da447e-227f-4507-a66e-b881178cf254"),
                            VehicleManufacturer = "Honda",
                            VehicleModel = "Civic",
                            VehicleName = "My Car1",
                            VehicleYear = 1970
                        },
                        new
                        {
                            PolicyId = new Guid("869f0281-68bc-4c8a-861e-eab060a10ad7"),
                            MemberId = new Guid("76da447e-227f-4507-a66e-b881178cf254"),
                            VehicleManufacturer = "Ford",
                            VehicleModel = "Mustang",
                            VehicleName = "My Car2",
                            VehicleYear = 1972
                        },
                        new
                        {
                            PolicyId = new Guid("c621403e-4c2a-4d31-a282-3970968d5f98"),
                            MemberId = new Guid("07e795a2-4df9-4885-80c6-a1a4ada01483"),
                            VehicleManufacturer = "Toyota",
                            VehicleModel = "Corolla",
                            VehicleName = "My Car",
                            VehicleYear = 1966
                        },
                        new
                        {
                            PolicyId = new Guid("3508732f-f3e5-48f5-8431-90e56fab44a1"),
                            MemberId = new Guid("07e795a2-4df9-4885-80c6-a1a4ada01483"),
                            VehicleManufacturer = "Ford",
                            VehicleModel = "Focus",
                            VehicleName = "My Car",
                            VehicleYear = 1955
                        },
                        new
                        {
                            PolicyId = new Guid("768ffdeb-42ed-4c24-ad68-2f0102e02360"),
                            MemberId = new Guid("07e795a2-4df9-4885-80c6-a1a4ada01483"),
                            VehicleManufacturer = "Chevy",
                            VehicleModel = "Impala",
                            VehicleName = "My Car",
                            VehicleYear = 1976
                        });
                });

            modelBuilder.Entity("SuperFormulaRestAPI.Data.Entities.Policy", b =>
                {
                    b.HasOne("SuperFormulaRestAPI.Data.Entities.Member", "Member")
                        .WithMany("Policies")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SuperFormulaRestAPI.Data.Entities.Member", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
