// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperFormulaRestAPI.Data;

#nullable disable

namespace SuperFormulaRestAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SuperFormulaRestAPI.Data.Entities.Member", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = new Guid("f315c0c2-f500-4c4b-bac0-f8a333f1257f"),
                            Address = "300 S Rankin St, Richmond, VA, 23224",
                            DriverLicenseNumber = "DL1000001",
                            FirstName = "Jon",
                            LastName = "Jones"
                        },
                        new
                        {
                            MemberId = new Guid("823546f0-0e44-472a-b307-419ef2ae6968"),
                            Address = "600 W Blazor St, Hanover, VA, 23225",
                            DriverLicenseNumber = "DL1000002",
                            FirstName = "Peter",
                            LastName = "Parker"
                        },
                        new
                        {
                            MemberId = new Guid("c2576ee3-f0cb-45a4-815f-8199af25bd72"),
                            Address = "400 E 35th St, New York, NY, 11232",
                            DriverLicenseNumber = "DL1000003",
                            FirstName = "Tony",
                            LastName = "Stark"
                        });
                });

            modelBuilder.Entity("SuperFormulaRestAPI.Data.Entities.Policy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Premium")
                        .HasColumnType("float");

                    b.Property<string>("VehicleManufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleYear")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.HasIndex("MemberId");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            PolicyId = new Guid("45e1658f-7530-4afb-a10d-62862ed124df"),
                            CreateDate = new DateTime(2022, 6, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(780),
                            EffectiveDate = new DateTime(2022, 7, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(809),
                            ExpirationDate = new DateTime(2022, 12, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(810),
                            MemberId = new Guid("f315c0c2-f500-4c4b-bac0-f8a333f1257f"),
                            Premium = 80.950000000000003,
                            VehicleManufacturer = "Toyota",
                            VehicleModel = "Camry",
                            VehicleName = "My Car",
                            VehicleYear = 1978
                        },
                        new
                        {
                            PolicyId = new Guid("0f045c1a-244d-4666-86e9-5b1ba088a771"),
                            CreateDate = new DateTime(2022, 6, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(815),
                            EffectiveDate = new DateTime(2022, 7, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(817),
                            ExpirationDate = new DateTime(2022, 12, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(818),
                            MemberId = new Guid("823546f0-0e44-472a-b307-419ef2ae6968"),
                            Premium = 80.950000000000003,
                            VehicleManufacturer = "Honda",
                            VehicleModel = "Civic",
                            VehicleName = "My Car1",
                            VehicleYear = 1970
                        },
                        new
                        {
                            PolicyId = new Guid("97471354-5d3c-4666-98f4-448e238d606f"),
                            CreateDate = new DateTime(2022, 6, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(822),
                            EffectiveDate = new DateTime(2022, 7, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(824),
                            ExpirationDate = new DateTime(2022, 12, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(825),
                            MemberId = new Guid("823546f0-0e44-472a-b307-419ef2ae6968"),
                            Premium = 80.950000000000003,
                            VehicleManufacturer = "Ford",
                            VehicleModel = "Mustang",
                            VehicleName = "My Car2",
                            VehicleYear = 1972
                        },
                        new
                        {
                            PolicyId = new Guid("a533d47b-41dc-43d6-9834-ec0c2e3c39d7"),
                            CreateDate = new DateTime(2022, 6, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(828),
                            EffectiveDate = new DateTime(2022, 7, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(829),
                            ExpirationDate = new DateTime(2022, 12, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(831),
                            MemberId = new Guid("c2576ee3-f0cb-45a4-815f-8199af25bd72"),
                            Premium = 80.950000000000003,
                            VehicleManufacturer = "Toyota",
                            VehicleModel = "Corolla",
                            VehicleName = "My Car",
                            VehicleYear = 1966
                        },
                        new
                        {
                            PolicyId = new Guid("850e38fc-404c-4767-bb08-acdef824e3c8"),
                            CreateDate = new DateTime(2022, 6, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(833),
                            EffectiveDate = new DateTime(2022, 7, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(835),
                            ExpirationDate = new DateTime(2022, 12, 1, 23, 44, 36, 558, DateTimeKind.Local).AddTicks(836),
                            MemberId = new Guid("c2576ee3-f0cb-45a4-815f-8199af25bd72"),
                            Premium = 80.950000000000003,
                            VehicleManufacturer = "Ford",
                            VehicleModel = "Focus",
                            VehicleName = "My Car",
                            VehicleYear = 1955
                        },
                        new
                        {
                            PolicyId = new Guid("54215567-7c33-4537-a665-9e28456dc728"),
                            CreateDate = new DateTime(2022, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2022, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2022, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = new Guid("c2576ee3-f0cb-45a4-815f-8199af25bd72"),
                            Premium = 80.950000000000003,
                            VehicleManufacturer = "Chevy",
                            VehicleModel = "Impala",
                            VehicleName = "My Car",
                            VehicleYear = 1976
                        });
                });

            modelBuilder.Entity("SuperFormulaRestAPI.Data.Entities.Policy", b =>
                {
                    b.HasOne("SuperFormulaRestAPI.Data.Entities.Member", "Member")
                        .WithMany("Policies")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SuperFormulaRestAPI.Data.Entities.Member", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
